/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server.msg.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CSBattleLogicFrameMsg implements org.apache.thrift.TBase<CSBattleLogicFrameMsg, CSBattleLogicFrameMsg._Fields>, java.io.Serializable, Cloneable, Comparable<CSBattleLogicFrameMsg> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CSBattleLogicFrameMsg");

  private static final org.apache.thrift.protocol.TField COMMAND_DATA_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("commandDataList", org.apache.thrift.protocol.TType.STRUCT, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CSBattleLogicFrameMsgStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CSBattleLogicFrameMsgTupleSchemeFactory());
  }

  public BattleCommandData commandDataList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    COMMAND_DATA_LIST((short)10, "commandDataList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 10: // COMMAND_DATA_LIST
          return COMMAND_DATA_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COMMAND_DATA_LIST, new org.apache.thrift.meta_data.FieldMetaData("commandDataList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BattleCommandData.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CSBattleLogicFrameMsg.class, metaDataMap);
  }

  public CSBattleLogicFrameMsg() {
  }

  public CSBattleLogicFrameMsg(
    BattleCommandData commandDataList)
  {
    this();
    this.commandDataList = commandDataList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CSBattleLogicFrameMsg(CSBattleLogicFrameMsg other) {
    if (other.isSetCommandDataList()) {
      this.commandDataList = new BattleCommandData(other.commandDataList);
    }
  }

  public CSBattleLogicFrameMsg deepCopy() {
    return new CSBattleLogicFrameMsg(this);
  }

  @Override
  public void clear() {
    this.commandDataList = null;
  }

  public BattleCommandData getCommandDataList() {
    return this.commandDataList;
  }

  public CSBattleLogicFrameMsg setCommandDataList(BattleCommandData commandDataList) {
    this.commandDataList = commandDataList;
    return this;
  }

  public void unsetCommandDataList() {
    this.commandDataList = null;
  }

  /** Returns true if field commandDataList is set (has been assigned a value) and false otherwise */
  public boolean isSetCommandDataList() {
    return this.commandDataList != null;
  }

  public void setCommandDataListIsSet(boolean value) {
    if (!value) {
      this.commandDataList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case COMMAND_DATA_LIST:
      if (value == null) {
        unsetCommandDataList();
      } else {
        setCommandDataList((BattleCommandData)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case COMMAND_DATA_LIST:
      return getCommandDataList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case COMMAND_DATA_LIST:
      return isSetCommandDataList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CSBattleLogicFrameMsg)
      return this.equals((CSBattleLogicFrameMsg)that);
    return false;
  }

  public boolean equals(CSBattleLogicFrameMsg that) {
    if (that == null)
      return false;

    boolean this_present_commandDataList = true && this.isSetCommandDataList();
    boolean that_present_commandDataList = true && that.isSetCommandDataList();
    if (this_present_commandDataList || that_present_commandDataList) {
      if (!(this_present_commandDataList && that_present_commandDataList))
        return false;
      if (!this.commandDataList.equals(that.commandDataList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(CSBattleLogicFrameMsg other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCommandDataList()).compareTo(other.isSetCommandDataList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommandDataList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.commandDataList, other.commandDataList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CSBattleLogicFrameMsg(");
    boolean first = true;

    sb.append("commandDataList:");
    if (this.commandDataList == null) {
      sb.append("null");
    } else {
      sb.append(this.commandDataList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (commandDataList != null) {
      commandDataList.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CSBattleLogicFrameMsgStandardSchemeFactory implements SchemeFactory {
    public CSBattleLogicFrameMsgStandardScheme getScheme() {
      return new CSBattleLogicFrameMsgStandardScheme();
    }
  }

  private static class CSBattleLogicFrameMsgStandardScheme extends StandardScheme<CSBattleLogicFrameMsg> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CSBattleLogicFrameMsg struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 10: // COMMAND_DATA_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.commandDataList = new BattleCommandData();
              struct.commandDataList.read(iprot);
              struct.setCommandDataListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CSBattleLogicFrameMsg struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.commandDataList != null) {
        oprot.writeFieldBegin(COMMAND_DATA_LIST_FIELD_DESC);
        struct.commandDataList.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CSBattleLogicFrameMsgTupleSchemeFactory implements SchemeFactory {
    public CSBattleLogicFrameMsgTupleScheme getScheme() {
      return new CSBattleLogicFrameMsgTupleScheme();
    }
  }

  private static class CSBattleLogicFrameMsgTupleScheme extends TupleScheme<CSBattleLogicFrameMsg> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CSBattleLogicFrameMsg struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCommandDataList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetCommandDataList()) {
        struct.commandDataList.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CSBattleLogicFrameMsg struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.commandDataList = new BattleCommandData();
        struct.commandDataList.read(iprot);
        struct.setCommandDataListIsSet(true);
      }
    }
  }

}

