/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server.msg.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CSBattleLogicFrame implements org.apache.thrift.TBase<CSBattleLogicFrame, CSBattleLogicFrame._Fields>, java.io.Serializable, Cloneable, Comparable<CSBattleLogicFrame> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CSBattleLogicFrame");

  private static final org.apache.thrift.protocol.TField COMMAND_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("commandData", org.apache.thrift.protocol.TType.STRUCT, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CSBattleLogicFrameStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CSBattleLogicFrameTupleSchemeFactory());
  }

  public BattleCommandData commandData; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    COMMAND_DATA((short)10, "commandData");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 10: // COMMAND_DATA
          return COMMAND_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COMMAND_DATA, new org.apache.thrift.meta_data.FieldMetaData("commandData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BattleCommandData.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CSBattleLogicFrame.class, metaDataMap);
  }

  public CSBattleLogicFrame() {
  }

  public CSBattleLogicFrame(
    BattleCommandData commandData)
  {
    this();
    this.commandData = commandData;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CSBattleLogicFrame(CSBattleLogicFrame other) {
    if (other.isSetCommandData()) {
      this.commandData = new BattleCommandData(other.commandData);
    }
  }

  public CSBattleLogicFrame deepCopy() {
    return new CSBattleLogicFrame(this);
  }

  @Override
  public void clear() {
    this.commandData = null;
  }

  public BattleCommandData getCommandData() {
    return this.commandData;
  }

  public CSBattleLogicFrame setCommandData(BattleCommandData commandData) {
    this.commandData = commandData;
    return this;
  }

  public void unsetCommandData() {
    this.commandData = null;
  }

  /** Returns true if field commandData is set (has been assigned a value) and false otherwise */
  public boolean isSetCommandData() {
    return this.commandData != null;
  }

  public void setCommandDataIsSet(boolean value) {
    if (!value) {
      this.commandData = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case COMMAND_DATA:
      if (value == null) {
        unsetCommandData();
      } else {
        setCommandData((BattleCommandData)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case COMMAND_DATA:
      return getCommandData();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case COMMAND_DATA:
      return isSetCommandData();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CSBattleLogicFrame)
      return this.equals((CSBattleLogicFrame)that);
    return false;
  }

  public boolean equals(CSBattleLogicFrame that) {
    if (that == null)
      return false;

    boolean this_present_commandData = true && this.isSetCommandData();
    boolean that_present_commandData = true && that.isSetCommandData();
    if (this_present_commandData || that_present_commandData) {
      if (!(this_present_commandData && that_present_commandData))
        return false;
      if (!this.commandData.equals(that.commandData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(CSBattleLogicFrame other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCommandData()).compareTo(other.isSetCommandData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommandData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.commandData, other.commandData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CSBattleLogicFrame(");
    boolean first = true;

    sb.append("commandData:");
    if (this.commandData == null) {
      sb.append("null");
    } else {
      sb.append(this.commandData);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (commandData != null) {
      commandData.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CSBattleLogicFrameStandardSchemeFactory implements SchemeFactory {
    public CSBattleLogicFrameStandardScheme getScheme() {
      return new CSBattleLogicFrameStandardScheme();
    }
  }

  private static class CSBattleLogicFrameStandardScheme extends StandardScheme<CSBattleLogicFrame> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CSBattleLogicFrame struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 10: // COMMAND_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.commandData = new BattleCommandData();
              struct.commandData.read(iprot);
              struct.setCommandDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CSBattleLogicFrame struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.commandData != null) {
        oprot.writeFieldBegin(COMMAND_DATA_FIELD_DESC);
        struct.commandData.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CSBattleLogicFrameTupleSchemeFactory implements SchemeFactory {
    public CSBattleLogicFrameTupleScheme getScheme() {
      return new CSBattleLogicFrameTupleScheme();
    }
  }

  private static class CSBattleLogicFrameTupleScheme extends TupleScheme<CSBattleLogicFrame> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CSBattleLogicFrame struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCommandData()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetCommandData()) {
        struct.commandData.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CSBattleLogicFrame struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.commandData = new BattleCommandData();
        struct.commandData.read(iprot);
        struct.setCommandDataIsSet(true);
      }
    }
  }

}

