/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server.msg.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CSCreateRoom implements org.apache.thrift.TBase<CSCreateRoom, CSCreateRoom._Fields>, java.io.Serializable, Cloneable, Comparable<CSCreateRoom> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CSCreateRoom");

  private static final org.apache.thrift.protocol.TField ROOM_INFORMATION_FIELD_DESC = new org.apache.thrift.protocol.TField("roomInformation", org.apache.thrift.protocol.TType.STRUCT, (short)10);
  private static final org.apache.thrift.protocol.TField PLAYER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("playerName", org.apache.thrift.protocol.TType.STRING, (short)20);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CSCreateRoomStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CSCreateRoomTupleSchemeFactory());
  }

  public server.msg.auto.RoomInfo roomInformation; // required
  public String playerName; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ROOM_INFORMATION((short)10, "roomInformation"),
    PLAYER_NAME((short)20, "playerName");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 10: // ROOM_INFORMATION
          return ROOM_INFORMATION;
        case 20: // PLAYER_NAME
          return PLAYER_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ROOM_INFORMATION, new org.apache.thrift.meta_data.FieldMetaData("roomInformation", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, server.msg.auto.RoomInfo.class)));
    tmpMap.put(_Fields.PLAYER_NAME, new org.apache.thrift.meta_data.FieldMetaData("playerName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CSCreateRoom.class, metaDataMap);
  }

  public CSCreateRoom() {
  }

  public CSCreateRoom(
    server.msg.auto.RoomInfo roomInformation,
    String playerName)
  {
    this();
    this.roomInformation = roomInformation;
    this.playerName = playerName;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CSCreateRoom(CSCreateRoom other) {
    if (other.isSetRoomInformation()) {
      this.roomInformation = new server.msg.auto.RoomInfo(other.roomInformation);
    }
    if (other.isSetPlayerName()) {
      this.playerName = other.playerName;
    }
  }

  public CSCreateRoom deepCopy() {
    return new CSCreateRoom(this);
  }

  @Override
  public void clear() {
    this.roomInformation = null;
    this.playerName = null;
  }

  public server.msg.auto.RoomInfo getRoomInformation() {
    return this.roomInformation;
  }

  public CSCreateRoom setRoomInformation(server.msg.auto.RoomInfo roomInformation) {
    this.roomInformation = roomInformation;
    return this;
  }

  public void unsetRoomInformation() {
    this.roomInformation = null;
  }

  /** Returns true if field roomInformation is set (has been assigned a value) and false otherwise */
  public boolean isSetRoomInformation() {
    return this.roomInformation != null;
  }

  public void setRoomInformationIsSet(boolean value) {
    if (!value) {
      this.roomInformation = null;
    }
  }

  public String getPlayerName() {
    return this.playerName;
  }

  public CSCreateRoom setPlayerName(String playerName) {
    this.playerName = playerName;
    return this;
  }

  public void unsetPlayerName() {
    this.playerName = null;
  }

  /** Returns true if field playerName is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayerName() {
    return this.playerName != null;
  }

  public void setPlayerNameIsSet(boolean value) {
    if (!value) {
      this.playerName = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ROOM_INFORMATION:
      if (value == null) {
        unsetRoomInformation();
      } else {
        setRoomInformation((server.msg.auto.RoomInfo)value);
      }
      break;

    case PLAYER_NAME:
      if (value == null) {
        unsetPlayerName();
      } else {
        setPlayerName((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ROOM_INFORMATION:
      return getRoomInformation();

    case PLAYER_NAME:
      return getPlayerName();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ROOM_INFORMATION:
      return isSetRoomInformation();
    case PLAYER_NAME:
      return isSetPlayerName();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CSCreateRoom)
      return this.equals((CSCreateRoom)that);
    return false;
  }

  public boolean equals(CSCreateRoom that) {
    if (that == null)
      return false;

    boolean this_present_roomInformation = true && this.isSetRoomInformation();
    boolean that_present_roomInformation = true && that.isSetRoomInformation();
    if (this_present_roomInformation || that_present_roomInformation) {
      if (!(this_present_roomInformation && that_present_roomInformation))
        return false;
      if (!this.roomInformation.equals(that.roomInformation))
        return false;
    }

    boolean this_present_playerName = true && this.isSetPlayerName();
    boolean that_present_playerName = true && that.isSetPlayerName();
    if (this_present_playerName || that_present_playerName) {
      if (!(this_present_playerName && that_present_playerName))
        return false;
      if (!this.playerName.equals(that.playerName))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(CSCreateRoom other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRoomInformation()).compareTo(other.isSetRoomInformation());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoomInformation()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roomInformation, other.roomInformation);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPlayerName()).compareTo(other.isSetPlayerName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayerName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.playerName, other.playerName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CSCreateRoom(");
    boolean first = true;

    sb.append("roomInformation:");
    if (this.roomInformation == null) {
      sb.append("null");
    } else {
      sb.append(this.roomInformation);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("playerName:");
    if (this.playerName == null) {
      sb.append("null");
    } else {
      sb.append(this.playerName);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (roomInformation != null) {
      roomInformation.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CSCreateRoomStandardSchemeFactory implements SchemeFactory {
    public CSCreateRoomStandardScheme getScheme() {
      return new CSCreateRoomStandardScheme();
    }
  }

  private static class CSCreateRoomStandardScheme extends StandardScheme<CSCreateRoom> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CSCreateRoom struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 10: // ROOM_INFORMATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.roomInformation = new server.msg.auto.RoomInfo();
              struct.roomInformation.read(iprot);
              struct.setRoomInformationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 20: // PLAYER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.playerName = iprot.readString();
              struct.setPlayerNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CSCreateRoom struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.roomInformation != null) {
        oprot.writeFieldBegin(ROOM_INFORMATION_FIELD_DESC);
        struct.roomInformation.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.playerName != null) {
        oprot.writeFieldBegin(PLAYER_NAME_FIELD_DESC);
        oprot.writeString(struct.playerName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CSCreateRoomTupleSchemeFactory implements SchemeFactory {
    public CSCreateRoomTupleScheme getScheme() {
      return new CSCreateRoomTupleScheme();
    }
  }

  private static class CSCreateRoomTupleScheme extends TupleScheme<CSCreateRoom> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CSCreateRoom struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRoomInformation()) {
        optionals.set(0);
      }
      if (struct.isSetPlayerName()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetRoomInformation()) {
        struct.roomInformation.write(oprot);
      }
      if (struct.isSetPlayerName()) {
        oprot.writeString(struct.playerName);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CSCreateRoom struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.roomInformation = new server.msg.auto.RoomInfo();
        struct.roomInformation.read(iprot);
        struct.setRoomInformationIsSet(true);
      }
      if (incoming.get(1)) {
        struct.playerName = iprot.readString();
        struct.setPlayerNameIsSet(true);
      }
    }
  }

}

