/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server.msg.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CSFire implements org.apache.thrift.TBase<CSFire, CSFire._Fields>, java.io.Serializable, Cloneable, Comparable<CSFire> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CSFire");

  private static final org.apache.thrift.protocol.TField PLAYER_UID_FIELD_DESC = new org.apache.thrift.protocol.TField("playerUid", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField FIRE_INFO_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("fireInfoList", org.apache.thrift.protocol.TType.LIST, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CSFireStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CSFireTupleSchemeFactory());
  }

  public int playerUid; // required
  public List<server.msg.auto.FireInfo> fireInfoList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PLAYER_UID((short)1, "playerUid"),
    FIRE_INFO_LIST((short)10, "fireInfoList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PLAYER_UID
          return PLAYER_UID;
        case 10: // FIRE_INFO_LIST
          return FIRE_INFO_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PLAYERUID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PLAYER_UID, new org.apache.thrift.meta_data.FieldMetaData("playerUid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIRE_INFO_LIST, new org.apache.thrift.meta_data.FieldMetaData("fireInfoList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, server.msg.auto.FireInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CSFire.class, metaDataMap);
  }

  public CSFire() {
  }

  public CSFire(
    int playerUid,
    List<server.msg.auto.FireInfo> fireInfoList)
  {
    this();
    this.playerUid = playerUid;
    setPlayerUidIsSet(true);
    this.fireInfoList = fireInfoList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CSFire(CSFire other) {
    __isset_bitfield = other.__isset_bitfield;
    this.playerUid = other.playerUid;
    if (other.isSetFireInfoList()) {
      List<server.msg.auto.FireInfo> __this__fireInfoList = new ArrayList<server.msg.auto.FireInfo>(other.fireInfoList.size());
      for (server.msg.auto.FireInfo other_element : other.fireInfoList) {
        __this__fireInfoList.add(new server.msg.auto.FireInfo(other_element));
      }
      this.fireInfoList = __this__fireInfoList;
    }
  }

  public CSFire deepCopy() {
    return new CSFire(this);
  }

  @Override
  public void clear() {
    setPlayerUidIsSet(false);
    this.playerUid = 0;
    this.fireInfoList = null;
  }

  public int getPlayerUid() {
    return this.playerUid;
  }

  public CSFire setPlayerUid(int playerUid) {
    this.playerUid = playerUid;
    setPlayerUidIsSet(true);
    return this;
  }

  public void unsetPlayerUid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PLAYERUID_ISSET_ID);
  }

  /** Returns true if field playerUid is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayerUid() {
    return EncodingUtils.testBit(__isset_bitfield, __PLAYERUID_ISSET_ID);
  }

  public void setPlayerUidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PLAYERUID_ISSET_ID, value);
  }

  public int getFireInfoListSize() {
    return (this.fireInfoList == null) ? 0 : this.fireInfoList.size();
  }

  public java.util.Iterator<server.msg.auto.FireInfo> getFireInfoListIterator() {
    return (this.fireInfoList == null) ? null : this.fireInfoList.iterator();
  }

  public void addToFireInfoList(server.msg.auto.FireInfo elem) {
    if (this.fireInfoList == null) {
      this.fireInfoList = new ArrayList<server.msg.auto.FireInfo>();
    }
    this.fireInfoList.add(elem);
  }

  public List<server.msg.auto.FireInfo> getFireInfoList() {
    return this.fireInfoList;
  }

  public CSFire setFireInfoList(List<server.msg.auto.FireInfo> fireInfoList) {
    this.fireInfoList = fireInfoList;
    return this;
  }

  public void unsetFireInfoList() {
    this.fireInfoList = null;
  }

  /** Returns true if field fireInfoList is set (has been assigned a value) and false otherwise */
  public boolean isSetFireInfoList() {
    return this.fireInfoList != null;
  }

  public void setFireInfoListIsSet(boolean value) {
    if (!value) {
      this.fireInfoList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PLAYER_UID:
      if (value == null) {
        unsetPlayerUid();
      } else {
        setPlayerUid((Integer)value);
      }
      break;

    case FIRE_INFO_LIST:
      if (value == null) {
        unsetFireInfoList();
      } else {
        setFireInfoList((List<server.msg.auto.FireInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PLAYER_UID:
      return Integer.valueOf(getPlayerUid());

    case FIRE_INFO_LIST:
      return getFireInfoList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PLAYER_UID:
      return isSetPlayerUid();
    case FIRE_INFO_LIST:
      return isSetFireInfoList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CSFire)
      return this.equals((CSFire)that);
    return false;
  }

  public boolean equals(CSFire that) {
    if (that == null)
      return false;

    boolean this_present_playerUid = true;
    boolean that_present_playerUid = true;
    if (this_present_playerUid || that_present_playerUid) {
      if (!(this_present_playerUid && that_present_playerUid))
        return false;
      if (this.playerUid != that.playerUid)
        return false;
    }

    boolean this_present_fireInfoList = true && this.isSetFireInfoList();
    boolean that_present_fireInfoList = true && that.isSetFireInfoList();
    if (this_present_fireInfoList || that_present_fireInfoList) {
      if (!(this_present_fireInfoList && that_present_fireInfoList))
        return false;
      if (!this.fireInfoList.equals(that.fireInfoList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(CSFire other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPlayerUid()).compareTo(other.isSetPlayerUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayerUid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.playerUid, other.playerUid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFireInfoList()).compareTo(other.isSetFireInfoList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFireInfoList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fireInfoList, other.fireInfoList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CSFire(");
    boolean first = true;

    sb.append("playerUid:");
    sb.append(this.playerUid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("fireInfoList:");
    if (this.fireInfoList == null) {
      sb.append("null");
    } else {
      sb.append(this.fireInfoList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CSFireStandardSchemeFactory implements SchemeFactory {
    public CSFireStandardScheme getScheme() {
      return new CSFireStandardScheme();
    }
  }

  private static class CSFireStandardScheme extends StandardScheme<CSFire> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CSFire struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PLAYER_UID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.playerUid = iprot.readI32();
              struct.setPlayerUidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // FIRE_INFO_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.fireInfoList = new ArrayList<server.msg.auto.FireInfo>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  server.msg.auto.FireInfo _elem2;
                  _elem2 = new server.msg.auto.FireInfo();
                  _elem2.read(iprot);
                  struct.fireInfoList.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setFireInfoListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CSFire struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PLAYER_UID_FIELD_DESC);
      oprot.writeI32(struct.playerUid);
      oprot.writeFieldEnd();
      if (struct.fireInfoList != null) {
        oprot.writeFieldBegin(FIRE_INFO_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.fireInfoList.size()));
          for (server.msg.auto.FireInfo _iter3 : struct.fireInfoList)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CSFireTupleSchemeFactory implements SchemeFactory {
    public CSFireTupleScheme getScheme() {
      return new CSFireTupleScheme();
    }
  }

  private static class CSFireTupleScheme extends TupleScheme<CSFire> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CSFire struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPlayerUid()) {
        optionals.set(0);
      }
      if (struct.isSetFireInfoList()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPlayerUid()) {
        oprot.writeI32(struct.playerUid);
      }
      if (struct.isSetFireInfoList()) {
        {
          oprot.writeI32(struct.fireInfoList.size());
          for (server.msg.auto.FireInfo _iter4 : struct.fireInfoList)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CSFire struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.playerUid = iprot.readI32();
        struct.setPlayerUidIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.fireInfoList = new ArrayList<server.msg.auto.FireInfo>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            server.msg.auto.FireInfo _elem7;
            _elem7 = new server.msg.auto.FireInfo();
            _elem7.read(iprot);
            struct.fireInfoList.add(_elem7);
          }
        }
        struct.setFireInfoListIsSet(true);
      }
    }
  }

}

