/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server.msg.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CSItemGenFundamental implements org.apache.thrift.TBase<CSItemGenFundamental, CSItemGenFundamental._Fields>, java.io.Serializable, Cloneable, Comparable<CSItemGenFundamental> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CSItemGenFundamental");

  private static final org.apache.thrift.protocol.TField GEN_FUNDAMENTAL_FIELD_DESC = new org.apache.thrift.protocol.TField("genFundamental", org.apache.thrift.protocol.TType.STRUCT, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CSItemGenFundamentalStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CSItemGenFundamentalTupleSchemeFactory());
  }

  public server.msg.auto.ItemGenFundamental genFundamental; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GEN_FUNDAMENTAL((short)10, "genFundamental");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 10: // GEN_FUNDAMENTAL
          return GEN_FUNDAMENTAL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GEN_FUNDAMENTAL, new org.apache.thrift.meta_data.FieldMetaData("genFundamental", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, server.msg.auto.ItemGenFundamental.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CSItemGenFundamental.class, metaDataMap);
  }

  public CSItemGenFundamental() {
  }

  public CSItemGenFundamental(
    server.msg.auto.ItemGenFundamental genFundamental)
  {
    this();
    this.genFundamental = genFundamental;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CSItemGenFundamental(CSItemGenFundamental other) {
    if (other.isSetGenFundamental()) {
      this.genFundamental = new server.msg.auto.ItemGenFundamental(other.genFundamental);
    }
  }

  public CSItemGenFundamental deepCopy() {
    return new CSItemGenFundamental(this);
  }

  @Override
  public void clear() {
    this.genFundamental = null;
  }

  public server.msg.auto.ItemGenFundamental getGenFundamental() {
    return this.genFundamental;
  }

  public CSItemGenFundamental setGenFundamental(server.msg.auto.ItemGenFundamental genFundamental) {
    this.genFundamental = genFundamental;
    return this;
  }

  public void unsetGenFundamental() {
    this.genFundamental = null;
  }

  /** Returns true if field genFundamental is set (has been assigned a value) and false otherwise */
  public boolean isSetGenFundamental() {
    return this.genFundamental != null;
  }

  public void setGenFundamentalIsSet(boolean value) {
    if (!value) {
      this.genFundamental = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case GEN_FUNDAMENTAL:
      if (value == null) {
        unsetGenFundamental();
      } else {
        setGenFundamental((server.msg.auto.ItemGenFundamental)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case GEN_FUNDAMENTAL:
      return getGenFundamental();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case GEN_FUNDAMENTAL:
      return isSetGenFundamental();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CSItemGenFundamental)
      return this.equals((CSItemGenFundamental)that);
    return false;
  }

  public boolean equals(CSItemGenFundamental that) {
    if (that == null)
      return false;

    boolean this_present_genFundamental = true && this.isSetGenFundamental();
    boolean that_present_genFundamental = true && that.isSetGenFundamental();
    if (this_present_genFundamental || that_present_genFundamental) {
      if (!(this_present_genFundamental && that_present_genFundamental))
        return false;
      if (!this.genFundamental.equals(that.genFundamental))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(CSItemGenFundamental other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetGenFundamental()).compareTo(other.isSetGenFundamental());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGenFundamental()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.genFundamental, other.genFundamental);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CSItemGenFundamental(");
    boolean first = true;

    sb.append("genFundamental:");
    if (this.genFundamental == null) {
      sb.append("null");
    } else {
      sb.append(this.genFundamental);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (genFundamental != null) {
      genFundamental.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CSItemGenFundamentalStandardSchemeFactory implements SchemeFactory {
    public CSItemGenFundamentalStandardScheme getScheme() {
      return new CSItemGenFundamentalStandardScheme();
    }
  }

  private static class CSItemGenFundamentalStandardScheme extends StandardScheme<CSItemGenFundamental> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CSItemGenFundamental struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 10: // GEN_FUNDAMENTAL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.genFundamental = new server.msg.auto.ItemGenFundamental();
              struct.genFundamental.read(iprot);
              struct.setGenFundamentalIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CSItemGenFundamental struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.genFundamental != null) {
        oprot.writeFieldBegin(GEN_FUNDAMENTAL_FIELD_DESC);
        struct.genFundamental.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CSItemGenFundamentalTupleSchemeFactory implements SchemeFactory {
    public CSItemGenFundamentalTupleScheme getScheme() {
      return new CSItemGenFundamentalTupleScheme();
    }
  }

  private static class CSItemGenFundamentalTupleScheme extends TupleScheme<CSItemGenFundamental> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CSItemGenFundamental struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetGenFundamental()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetGenFundamental()) {
        struct.genFundamental.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CSItemGenFundamental struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.genFundamental = new server.msg.auto.ItemGenFundamental();
        struct.genFundamental.read(iprot);
        struct.setGenFundamentalIsSet(true);
      }
    }
  }

}

