/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server.msg.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MessageIdConstants {

  public static final int CS_PING = 103001;

  public static final int SC_PONG = 103002;

  public static final int CS_HANDLER = 103003;

  public static final int SC_HANDLER = 103004;

  public static final int CS_FIRE = 103005;

  public static final int SC_FIRE = 103006;

  public static final int CS_RoomList = 103007;

  public static final int SC_RoomList = 103008;

  public static final int CS_SearchRoom = 103009;

  public static final int SC_SearchRoom = 103010;

  public static final int CS_CreateRoom = 103011;

  public static final int SC_CreateRoom = 103012;

  public static final int CS_EnterRoom = 103013;

  public static final int SC_EnterRoom = 103014;

  public static final int SC_SyncPlayerInfo = 103015;

  public static final int CS_BattleLoadEnd = 103016;

  public static final int SC_BeginLoadBattle = 103017;

  public static final int SC_BattleBegin = 103018;

  public static final int SC_BattleEnd = 103019;

  public static final int CS_Hurt = 103020;

  public static final int SC_Hurt = 103021;

  public static final int CS_BattleEnd = 103022;

}
