/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server.msg.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SCBattleLogicFrame implements org.apache.thrift.TBase<SCBattleLogicFrame, SCBattleLogicFrame._Fields>, java.io.Serializable, Cloneable, Comparable<SCBattleLogicFrame> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SCBattleLogicFrame");

  private static final org.apache.thrift.protocol.TField BATTLE_FRAME_DATA_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("battleFrameDataList", org.apache.thrift.protocol.TType.LIST, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SCBattleLogicFrameStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SCBattleLogicFrameTupleSchemeFactory());
  }

  public List<BattleFrameData> battleFrameDataList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BATTLE_FRAME_DATA_LIST((short)10, "battleFrameDataList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 10: // BATTLE_FRAME_DATA_LIST
          return BATTLE_FRAME_DATA_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BATTLE_FRAME_DATA_LIST, new org.apache.thrift.meta_data.FieldMetaData("battleFrameDataList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BattleFrameData.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SCBattleLogicFrame.class, metaDataMap);
  }

  public SCBattleLogicFrame() {
  }

  public SCBattleLogicFrame(
    List<BattleFrameData> battleFrameDataList)
  {
    this();
    this.battleFrameDataList = battleFrameDataList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SCBattleLogicFrame(SCBattleLogicFrame other) {
    if (other.isSetBattleFrameDataList()) {
      List<BattleFrameData> __this__battleFrameDataList = new ArrayList<BattleFrameData>(other.battleFrameDataList.size());
      for (BattleFrameData other_element : other.battleFrameDataList) {
        __this__battleFrameDataList.add(new BattleFrameData(other_element));
      }
      this.battleFrameDataList = __this__battleFrameDataList;
    }
  }

  public SCBattleLogicFrame deepCopy() {
    return new SCBattleLogicFrame(this);
  }

  @Override
  public void clear() {
    this.battleFrameDataList = null;
  }

  public int getBattleFrameDataListSize() {
    return (this.battleFrameDataList == null) ? 0 : this.battleFrameDataList.size();
  }

  public java.util.Iterator<BattleFrameData> getBattleFrameDataListIterator() {
    return (this.battleFrameDataList == null) ? null : this.battleFrameDataList.iterator();
  }

  public void addToBattleFrameDataList(BattleFrameData elem) {
    if (this.battleFrameDataList == null) {
      this.battleFrameDataList = new ArrayList<BattleFrameData>();
    }
    this.battleFrameDataList.add(elem);
  }

  public List<BattleFrameData> getBattleFrameDataList() {
    return this.battleFrameDataList;
  }

  public SCBattleLogicFrame setBattleFrameDataList(List<BattleFrameData> battleFrameDataList) {
    this.battleFrameDataList = battleFrameDataList;
    return this;
  }

  public void unsetBattleFrameDataList() {
    this.battleFrameDataList = null;
  }

  /** Returns true if field battleFrameDataList is set (has been assigned a value) and false otherwise */
  public boolean isSetBattleFrameDataList() {
    return this.battleFrameDataList != null;
  }

  public void setBattleFrameDataListIsSet(boolean value) {
    if (!value) {
      this.battleFrameDataList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BATTLE_FRAME_DATA_LIST:
      if (value == null) {
        unsetBattleFrameDataList();
      } else {
        setBattleFrameDataList((List<BattleFrameData>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BATTLE_FRAME_DATA_LIST:
      return getBattleFrameDataList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BATTLE_FRAME_DATA_LIST:
      return isSetBattleFrameDataList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SCBattleLogicFrame)
      return this.equals((SCBattleLogicFrame)that);
    return false;
  }

  public boolean equals(SCBattleLogicFrame that) {
    if (that == null)
      return false;

    boolean this_present_battleFrameDataList = true && this.isSetBattleFrameDataList();
    boolean that_present_battleFrameDataList = true && that.isSetBattleFrameDataList();
    if (this_present_battleFrameDataList || that_present_battleFrameDataList) {
      if (!(this_present_battleFrameDataList && that_present_battleFrameDataList))
        return false;
      if (!this.battleFrameDataList.equals(that.battleFrameDataList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SCBattleLogicFrame other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBattleFrameDataList()).compareTo(other.isSetBattleFrameDataList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBattleFrameDataList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.battleFrameDataList, other.battleFrameDataList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SCBattleLogicFrame(");
    boolean first = true;

    sb.append("battleFrameDataList:");
    if (this.battleFrameDataList == null) {
      sb.append("null");
    } else {
      sb.append(this.battleFrameDataList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SCBattleLogicFrameStandardSchemeFactory implements SchemeFactory {
    public SCBattleLogicFrameStandardScheme getScheme() {
      return new SCBattleLogicFrameStandardScheme();
    }
  }

  private static class SCBattleLogicFrameStandardScheme extends StandardScheme<SCBattleLogicFrame> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SCBattleLogicFrame struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 10: // BATTLE_FRAME_DATA_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.battleFrameDataList = new ArrayList<BattleFrameData>(_list16.size);
                for (int _i17 = 0; _i17 < _list16.size; ++_i17)
                {
                  BattleFrameData _elem18;
                  _elem18 = new BattleFrameData();
                  _elem18.read(iprot);
                  struct.battleFrameDataList.add(_elem18);
                }
                iprot.readListEnd();
              }
              struct.setBattleFrameDataListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SCBattleLogicFrame struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.battleFrameDataList != null) {
        oprot.writeFieldBegin(BATTLE_FRAME_DATA_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.battleFrameDataList.size()));
          for (BattleFrameData _iter19 : struct.battleFrameDataList)
          {
            _iter19.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SCBattleLogicFrameTupleSchemeFactory implements SchemeFactory {
    public SCBattleLogicFrameTupleScheme getScheme() {
      return new SCBattleLogicFrameTupleScheme();
    }
  }

  private static class SCBattleLogicFrameTupleScheme extends TupleScheme<SCBattleLogicFrame> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SCBattleLogicFrame struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBattleFrameDataList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetBattleFrameDataList()) {
        {
          oprot.writeI32(struct.battleFrameDataList.size());
          for (BattleFrameData _iter20 : struct.battleFrameDataList)
          {
            _iter20.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SCBattleLogicFrame struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.battleFrameDataList = new ArrayList<BattleFrameData>(_list21.size);
          for (int _i22 = 0; _i22 < _list21.size; ++_i22)
          {
            BattleFrameData _elem23;
            _elem23 = new BattleFrameData();
            _elem23.read(iprot);
            struct.battleFrameDataList.add(_elem23);
          }
        }
        struct.setBattleFrameDataListIsSet(true);
      }
    }
  }

}

