/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server.msg.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SCBattleBegin implements org.apache.thrift.TBase<SCBattleBegin, SCBattleBegin._Fields>, java.io.Serializable, Cloneable, Comparable<SCBattleBegin> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SCBattleBegin");

  private static final org.apache.thrift.protocol.TField CD_FIELD_DESC = new org.apache.thrift.protocol.TField("cd", org.apache.thrift.protocol.TType.I32, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SCBattleBeginStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SCBattleBeginTupleSchemeFactory());
  }

  public int cd; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CD((short)10, "cd");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 10: // CD
          return CD;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CD_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CD, new org.apache.thrift.meta_data.FieldMetaData("cd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SCBattleBegin.class, metaDataMap);
  }

  public SCBattleBegin() {
  }

  public SCBattleBegin(
    int cd)
  {
    this();
    this.cd = cd;
    setCdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SCBattleBegin(SCBattleBegin other) {
    __isset_bitfield = other.__isset_bitfield;
    this.cd = other.cd;
  }

  public SCBattleBegin deepCopy() {
    return new SCBattleBegin(this);
  }

  @Override
  public void clear() {
    setCdIsSet(false);
    this.cd = 0;
  }

  public int getCd() {
    return this.cd;
  }

  public SCBattleBegin setCd(int cd) {
    this.cd = cd;
    setCdIsSet(true);
    return this;
  }

  public void unsetCd() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CD_ISSET_ID);
  }

  /** Returns true if field cd is set (has been assigned a value) and false otherwise */
  public boolean isSetCd() {
    return EncodingUtils.testBit(__isset_bitfield, __CD_ISSET_ID);
  }

  public void setCdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CD_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CD:
      if (value == null) {
        unsetCd();
      } else {
        setCd((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CD:
      return Integer.valueOf(getCd());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CD:
      return isSetCd();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SCBattleBegin)
      return this.equals((SCBattleBegin)that);
    return false;
  }

  public boolean equals(SCBattleBegin that) {
    if (that == null)
      return false;

    boolean this_present_cd = true;
    boolean that_present_cd = true;
    if (this_present_cd || that_present_cd) {
      if (!(this_present_cd && that_present_cd))
        return false;
      if (this.cd != that.cd)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SCBattleBegin other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCd()).compareTo(other.isSetCd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cd, other.cd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SCBattleBegin(");
    boolean first = true;

    sb.append("cd:");
    sb.append(this.cd);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SCBattleBeginStandardSchemeFactory implements SchemeFactory {
    public SCBattleBeginStandardScheme getScheme() {
      return new SCBattleBeginStandardScheme();
    }
  }

  private static class SCBattleBeginStandardScheme extends StandardScheme<SCBattleBegin> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SCBattleBegin struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 10: // CD
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.cd = iprot.readI32();
              struct.setCdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SCBattleBegin struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CD_FIELD_DESC);
      oprot.writeI32(struct.cd);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SCBattleBeginTupleSchemeFactory implements SchemeFactory {
    public SCBattleBeginTupleScheme getScheme() {
      return new SCBattleBeginTupleScheme();
    }
  }

  private static class SCBattleBeginTupleScheme extends TupleScheme<SCBattleBegin> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SCBattleBegin struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCd()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetCd()) {
        oprot.writeI32(struct.cd);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SCBattleBegin struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.cd = iprot.readI32();
        struct.setCdIsSet(true);
      }
    }
  }

}

