/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server.msg.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SCRoomList implements org.apache.thrift.TBase<SCRoomList, SCRoomList._Fields>, java.io.Serializable, Cloneable, Comparable<SCRoomList> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SCRoomList");

  private static final org.apache.thrift.protocol.TField ROOM_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("roomList", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SCRoomListStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SCRoomListTupleSchemeFactory());
  }

  public List<server.msg.auto.RoomInfo> roomList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ROOM_LIST((short)1, "roomList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ROOM_LIST
          return ROOM_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ROOM_LIST, new org.apache.thrift.meta_data.FieldMetaData("roomList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, server.msg.auto.RoomInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SCRoomList.class, metaDataMap);
  }

  public SCRoomList() {
  }

  public SCRoomList(
    List<server.msg.auto.RoomInfo> roomList)
  {
    this();
    this.roomList = roomList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SCRoomList(SCRoomList other) {
    if (other.isSetRoomList()) {
      List<server.msg.auto.RoomInfo> __this__roomList = new ArrayList<server.msg.auto.RoomInfo>(other.roomList.size());
      for (server.msg.auto.RoomInfo other_element : other.roomList) {
        __this__roomList.add(new server.msg.auto.RoomInfo(other_element));
      }
      this.roomList = __this__roomList;
    }
  }

  public SCRoomList deepCopy() {
    return new SCRoomList(this);
  }

  @Override
  public void clear() {
    this.roomList = null;
  }

  public int getRoomListSize() {
    return (this.roomList == null) ? 0 : this.roomList.size();
  }

  public java.util.Iterator<server.msg.auto.RoomInfo> getRoomListIterator() {
    return (this.roomList == null) ? null : this.roomList.iterator();
  }

  public void addToRoomList(server.msg.auto.RoomInfo elem) {
    if (this.roomList == null) {
      this.roomList = new ArrayList<server.msg.auto.RoomInfo>();
    }
    this.roomList.add(elem);
  }

  public List<server.msg.auto.RoomInfo> getRoomList() {
    return this.roomList;
  }

  public SCRoomList setRoomList(List<server.msg.auto.RoomInfo> roomList) {
    this.roomList = roomList;
    return this;
  }

  public void unsetRoomList() {
    this.roomList = null;
  }

  /** Returns true if field roomList is set (has been assigned a value) and false otherwise */
  public boolean isSetRoomList() {
    return this.roomList != null;
  }

  public void setRoomListIsSet(boolean value) {
    if (!value) {
      this.roomList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ROOM_LIST:
      if (value == null) {
        unsetRoomList();
      } else {
        setRoomList((List<server.msg.auto.RoomInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ROOM_LIST:
      return getRoomList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ROOM_LIST:
      return isSetRoomList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SCRoomList)
      return this.equals((SCRoomList)that);
    return false;
  }

  public boolean equals(SCRoomList that) {
    if (that == null)
      return false;

    boolean this_present_roomList = true && this.isSetRoomList();
    boolean that_present_roomList = true && that.isSetRoomList();
    if (this_present_roomList || that_present_roomList) {
      if (!(this_present_roomList && that_present_roomList))
        return false;
      if (!this.roomList.equals(that.roomList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SCRoomList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRoomList()).compareTo(other.isSetRoomList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoomList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roomList, other.roomList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SCRoomList(");
    boolean first = true;

    sb.append("roomList:");
    if (this.roomList == null) {
      sb.append("null");
    } else {
      sb.append(this.roomList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SCRoomListStandardSchemeFactory implements SchemeFactory {
    public SCRoomListStandardScheme getScheme() {
      return new SCRoomListStandardScheme();
    }
  }

  private static class SCRoomListStandardScheme extends StandardScheme<SCRoomList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SCRoomList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ROOM_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.roomList = new ArrayList<server.msg.auto.RoomInfo>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  server.msg.auto.RoomInfo _elem2;
                  _elem2 = new server.msg.auto.RoomInfo();
                  _elem2.read(iprot);
                  struct.roomList.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setRoomListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SCRoomList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.roomList != null) {
        oprot.writeFieldBegin(ROOM_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.roomList.size()));
          for (server.msg.auto.RoomInfo _iter3 : struct.roomList)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SCRoomListTupleSchemeFactory implements SchemeFactory {
    public SCRoomListTupleScheme getScheme() {
      return new SCRoomListTupleScheme();
    }
  }

  private static class SCRoomListTupleScheme extends TupleScheme<SCRoomList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SCRoomList struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRoomList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetRoomList()) {
        {
          oprot.writeI32(struct.roomList.size());
          for (server.msg.auto.RoomInfo _iter4 : struct.roomList)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SCRoomList struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.roomList = new ArrayList<server.msg.auto.RoomInfo>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            server.msg.auto.RoomInfo _elem7;
            _elem7 = new server.msg.auto.RoomInfo();
            _elem7.read(iprot);
            struct.roomList.add(_elem7);
          }
        }
        struct.setRoomListIsSet(true);
      }
    }
  }

}

