/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server.msg.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SCSyncPlayerInfo implements org.apache.thrift.TBase<SCSyncPlayerInfo, SCSyncPlayerInfo._Fields>, java.io.Serializable, Cloneable, Comparable<SCSyncPlayerInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SCSyncPlayerInfo");

  private static final org.apache.thrift.protocol.TField PLAYER_INFOMATION_FIELD_DESC = new org.apache.thrift.protocol.TField("playerInfomation", org.apache.thrift.protocol.TType.STRUCT, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SCSyncPlayerInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SCSyncPlayerInfoTupleSchemeFactory());
  }

  public server.msg.auto.PlayerInfo playerInfomation; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PLAYER_INFOMATION((short)10, "playerInfomation");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 10: // PLAYER_INFOMATION
          return PLAYER_INFOMATION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PLAYER_INFOMATION, new org.apache.thrift.meta_data.FieldMetaData("playerInfomation", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, server.msg.auto.PlayerInfo.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SCSyncPlayerInfo.class, metaDataMap);
  }

  public SCSyncPlayerInfo() {
  }

  public SCSyncPlayerInfo(
    server.msg.auto.PlayerInfo playerInfomation)
  {
    this();
    this.playerInfomation = playerInfomation;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SCSyncPlayerInfo(SCSyncPlayerInfo other) {
    if (other.isSetPlayerInfomation()) {
      this.playerInfomation = new server.msg.auto.PlayerInfo(other.playerInfomation);
    }
  }

  public SCSyncPlayerInfo deepCopy() {
    return new SCSyncPlayerInfo(this);
  }

  @Override
  public void clear() {
    this.playerInfomation = null;
  }

  public server.msg.auto.PlayerInfo getPlayerInfomation() {
    return this.playerInfomation;
  }

  public SCSyncPlayerInfo setPlayerInfomation(server.msg.auto.PlayerInfo playerInfomation) {
    this.playerInfomation = playerInfomation;
    return this;
  }

  public void unsetPlayerInfomation() {
    this.playerInfomation = null;
  }

  /** Returns true if field playerInfomation is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayerInfomation() {
    return this.playerInfomation != null;
  }

  public void setPlayerInfomationIsSet(boolean value) {
    if (!value) {
      this.playerInfomation = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PLAYER_INFOMATION:
      if (value == null) {
        unsetPlayerInfomation();
      } else {
        setPlayerInfomation((server.msg.auto.PlayerInfo)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PLAYER_INFOMATION:
      return getPlayerInfomation();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PLAYER_INFOMATION:
      return isSetPlayerInfomation();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SCSyncPlayerInfo)
      return this.equals((SCSyncPlayerInfo)that);
    return false;
  }

  public boolean equals(SCSyncPlayerInfo that) {
    if (that == null)
      return false;

    boolean this_present_playerInfomation = true && this.isSetPlayerInfomation();
    boolean that_present_playerInfomation = true && that.isSetPlayerInfomation();
    if (this_present_playerInfomation || that_present_playerInfomation) {
      if (!(this_present_playerInfomation && that_present_playerInfomation))
        return false;
      if (!this.playerInfomation.equals(that.playerInfomation))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SCSyncPlayerInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPlayerInfomation()).compareTo(other.isSetPlayerInfomation());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayerInfomation()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.playerInfomation, other.playerInfomation);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SCSyncPlayerInfo(");
    boolean first = true;

    sb.append("playerInfomation:");
    if (this.playerInfomation == null) {
      sb.append("null");
    } else {
      sb.append(this.playerInfomation);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (playerInfomation != null) {
      playerInfomation.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SCSyncPlayerInfoStandardSchemeFactory implements SchemeFactory {
    public SCSyncPlayerInfoStandardScheme getScheme() {
      return new SCSyncPlayerInfoStandardScheme();
    }
  }

  private static class SCSyncPlayerInfoStandardScheme extends StandardScheme<SCSyncPlayerInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SCSyncPlayerInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 10: // PLAYER_INFOMATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.playerInfomation = new server.msg.auto.PlayerInfo();
              struct.playerInfomation.read(iprot);
              struct.setPlayerInfomationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SCSyncPlayerInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.playerInfomation != null) {
        oprot.writeFieldBegin(PLAYER_INFOMATION_FIELD_DESC);
        struct.playerInfomation.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SCSyncPlayerInfoTupleSchemeFactory implements SchemeFactory {
    public SCSyncPlayerInfoTupleScheme getScheme() {
      return new SCSyncPlayerInfoTupleScheme();
    }
  }

  private static class SCSyncPlayerInfoTupleScheme extends TupleScheme<SCSyncPlayerInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SCSyncPlayerInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPlayerInfomation()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPlayerInfomation()) {
        struct.playerInfomation.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SCSyncPlayerInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.playerInfomation = new server.msg.auto.PlayerInfo();
        struct.playerInfomation.read(iprot);
        struct.setPlayerInfomationIsSet(true);
      }
    }
  }

}

